/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author javam2019
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        DesktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CambiarUsuario = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jEditMenu = new javax.swing.JMenu();
        cutMenuCategorias = new javax.swing.JMenuItem();
        cutMenuSubCategorias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cutMenuAsociados = new javax.swing.JMenuItem();
        cutMenuEmpleados = new javax.swing.JMenuItem();
        cutMenuNivelesAcademicos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cutMenuServicios = new javax.swing.JMenuItem();
        cutMenuServiciosPrestados = new javax.swing.JMenuItem();
        cutMenuServiciosMunicipales = new javax.swing.JMenuItem();
        cutMenuServiciosMunicipales1 = new javax.swing.JMenuItem();
        jEditMenu1 = new javax.swing.JMenu();
        cutMenuMunicipios = new javax.swing.JMenuItem();
        cutMenuDepartamentos = new javax.swing.JMenuItem();
        cutMenuRegiones = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Sesion");

        CambiarUsuario.setMnemonic('o');
        CambiarUsuario.setText("Cambiar usuario");
        fileMenu.add(CambiarUsuario);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jEditMenu.setMnemonic('e');
        jEditMenu.setText("Opciones");

        cutMenuCategorias.setMnemonic('t');
        cutMenuCategorias.setText("Categorias");
        cutMenuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuCategoriasActionPerformed(evt);
            }
        });
        jEditMenu.add(cutMenuCategorias);

        cutMenuSubCategorias.setMnemonic('y');
        cutMenuSubCategorias.setText("Sub Categorias");
        cutMenuSubCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuSubCategoriasActionPerformed(evt);
            }
        });
        jEditMenu.add(cutMenuSubCategorias);

        menuBar.add(jEditMenu);

        jMenu3.setText("Personas");

        cutMenuAsociados.setMnemonic('y');
        cutMenuAsociados.setText("Asociados Pendientes");
        jMenu3.add(cutMenuAsociados);

        cutMenuEmpleados.setMnemonic('y');
        cutMenuEmpleados.setText("Empleados");
        jMenu3.add(cutMenuEmpleados);

        cutMenuNivelesAcademicos.setMnemonic('y');
        cutMenuNivelesAcademicos.setText("Niveles Academicos");
        jMenu3.add(cutMenuNivelesAcademicos);

        menuBar.add(jMenu3);

        jMenu4.setText("Servicios");

        cutMenuServicios.setMnemonic('y');
        cutMenuServicios.setText("Servicios");
        cutMenuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuServiciosActionPerformed(evt);
            }
        });
        jMenu4.add(cutMenuServicios);

        cutMenuServiciosPrestados.setMnemonic('y');
        cutMenuServiciosPrestados.setText("Servicios Prestados");
        jMenu4.add(cutMenuServiciosPrestados);

        cutMenuServiciosMunicipales.setMnemonic('y');
        cutMenuServiciosMunicipales.setText("Servicios Municipales");
        jMenu4.add(cutMenuServiciosMunicipales);

        cutMenuServiciosMunicipales1.setMnemonic('y');
        cutMenuServiciosMunicipales1.setText("Tipo Costo");
        jMenu4.add(cutMenuServiciosMunicipales1);

        menuBar.add(jMenu4);

        jEditMenu1.setMnemonic('e');
        jEditMenu1.setText("Area");

        cutMenuMunicipios.setMnemonic('t');
        cutMenuMunicipios.setText("Municipios");
        cutMenuMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuMunicipiosActionPerformed(evt);
            }
        });
        jEditMenu1.add(cutMenuMunicipios);

        cutMenuDepartamentos.setMnemonic('y');
        cutMenuDepartamentos.setText("Departamentos");
        cutMenuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuDepartamentosActionPerformed(evt);
            }
        });
        jEditMenu1.add(cutMenuDepartamentos);

        cutMenuRegiones.setMnemonic('y');
        cutMenuRegiones.setText("Regiones");
        cutMenuRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuRegionesActionPerformed(evt);
            }
        });
        jEditMenu1.add(cutMenuRegiones);

        menuBar.add(jEditMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cutMenuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuCategoriasActionPerformed

    private void cutMenuMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuMunicipiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuMunicipiosActionPerformed

    private void cutMenuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuDepartamentosActionPerformed

    private void cutMenuRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuRegionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuRegionesActionPerformed

    private void cutMenuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuServiciosActionPerformed

    private void cutMenuSubCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuSubCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuSubCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CambiarUsuario;
    public javax.swing.JDesktopPane DesktopPane;
    public javax.swing.JMenuItem cutMenuAsociados;
    public javax.swing.JMenuItem cutMenuCategorias;
    public javax.swing.JMenuItem cutMenuDepartamentos;
    public javax.swing.JMenuItem cutMenuEmpleados;
    public javax.swing.JMenuItem cutMenuMunicipios;
    public javax.swing.JMenuItem cutMenuNivelesAcademicos;
    public javax.swing.JMenuItem cutMenuRegiones;
    public javax.swing.JMenuItem cutMenuServicios;
    public javax.swing.JMenuItem cutMenuServiciosMunicipales;
    public javax.swing.JMenuItem cutMenuServiciosMunicipales1;
    public javax.swing.JMenuItem cutMenuServiciosPrestados;
    public javax.swing.JMenuItem cutMenuSubCategorias;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    public javax.swing.JMenu jEditMenu;
    private javax.swing.JMenu jEditMenu1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
