/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class VistaSubCategorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaSubCategorias
     */
    public VistaSubCategorias() {
        initComponents();
        String ruta = new File ("").getAbsolutePath () + "\\src\\imagenes\\subcate.png";
        System.out.println("Ruta: " + ruta);
        jLblmagenes.setIcon(new ImageIcon(ruta));
        //setSize(780, 650);
        //JOptionPane.showMessageDialog(null, System.getProperty("user.dir"));
        this.getContentPane().setBackground(Color.orange);
        //setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLblSubId = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jTxtSubcategoria = new javax.swing.JTextField();
        jTxtNombreSub = new javax.swing.JTextField();
        jLblCategoria = new javax.swing.JLabel();
        jLblEmpleado = new javax.swing.JLabel();
        jTxtCategoria = new javax.swing.JTextField();
        jTxtEmpleado = new javax.swing.JTextField();
        jBtnBuscarSub = new javax.swing.JButton();
        jBtnModificarSub = new javax.swing.JButton();
        jBtnGuardarSub = new javax.swing.JButton();
        jBtnEliminarSub = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListarSubcate = new javax.swing.JTable();
        jLblSubtitulo = new javax.swing.JLabel();
        jLblmagenes = new javax.swing.JLabel();
        jLblCategoria1 = new javax.swing.JLabel();
        jCmbCategoria = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("SUBCATEGORIAS");

        jLblSubId.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblSubId.setForeground(new java.awt.Color(0, 0, 255));
        jLblSubId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblSubId.setText("SUBCATEGORIA_ID");

        jLblNombre.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblNombre.setForeground(new java.awt.Color(0, 0, 255));
        jLblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblNombre.setText("SUBCATEGORIA_NOMBRE");

        jLblCategoria.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblCategoria.setForeground(new java.awt.Color(0, 0, 255));
        jLblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblCategoria.setText("CATEGORIA_ID");

        jLblEmpleado.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblEmpleado.setForeground(new java.awt.Color(0, 0, 255));
        jLblEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblEmpleado.setText("EMPLEADO_ID");

        jBtnBuscarSub.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jBtnBuscarSub.setForeground(new java.awt.Color(255, 0, 255));
        jBtnBuscarSub.setText("BUSCAR");

        jBtnModificarSub.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jBtnModificarSub.setForeground(new java.awt.Color(255, 0, 255));
        jBtnModificarSub.setText("MODIFICAR");

        jBtnGuardarSub.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jBtnGuardarSub.setForeground(new java.awt.Color(255, 0, 255));
        jBtnGuardarSub.setText("GUARDAR");

        jBtnEliminarSub.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jBtnEliminarSub.setForeground(new java.awt.Color(255, 0, 255));
        jBtnEliminarSub.setText("ELIMINAR");

        jTblListarSubcate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblListarSubcate);

        jLblSubtitulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblSubtitulo.setText("LISTAR SUBCATEGORIAS");

        jLblmagenes.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLblmagenes.setForeground(new java.awt.Color(255, 0, 0));
        jLblmagenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLblCategoria1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLblCategoria1.setForeground(new java.awt.Color(0, 0, 255));
        jLblCategoria1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblCategoria1.setText("CATEGORIA_ID");

        jCmbCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLblSubId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jTxtSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLblNombre)
                                .addGap(58, 58, 58)
                                .addComponent(jTxtNombreSub, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jTxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jTxtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLblmagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jBtnGuardarSub)
                        .addGap(47, 47, 47)
                        .addComponent(jBtnModificarSub)
                        .addGap(40, 40, 40)
                        .addComponent(jBtnEliminarSub))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBtnBuscarSub)
                        .addGap(18, 18, 18)
                        .addComponent(jLblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCategoria)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jCmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLblSubId))
                            .addComponent(jTxtSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTxtNombreSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLblCategoria1))
                            .addComponent(jTxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEmpleado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTxtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLblmagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnGuardarSub)
                    .addComponent(jBtnModificarSub)
                    .addComponent(jBtnEliminarSub))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBuscarSub)
                    .addComponent(jLblSubtitulo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSubCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSubCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSubCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSubCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSubCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnBuscarSub;
    public javax.swing.JButton jBtnEliminarSub;
    public javax.swing.JButton jBtnGuardarSub;
    public javax.swing.JButton jBtnModificarSub;
    public javax.swing.JComboBox<String> jCmbCategoria;
    private javax.swing.JLabel jLblCategoria;
    private javax.swing.JLabel jLblCategoria1;
    private javax.swing.JLabel jLblEmpleado;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblSubId;
    private javax.swing.JLabel jLblSubtitulo;
    public javax.swing.JLabel jLblTitulo;
    public javax.swing.JLabel jLblmagenes;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTblListarSubcate;
    public javax.swing.JTextField jTxtCategoria;
    public javax.swing.JTextField jTxtEmpleado;
    public javax.swing.JTextField jTxtNombreSub;
    public javax.swing.JTextField jTxtSubcategoria;
    // End of variables declaration//GEN-END:variables
}
